export { default as ClassificaHoraInput } from './classificahora.input';
export { default as ClassificaTarInput } from './classificatar.input';
export { default as HoraTarefaInput } from './horatarefa.input';
export { default as ObservacaoTarInput } from './observacaotar.input';
export { default as SetorInput } from './setor.input';
export { default as TarefaInput } from './tarefa.input';
export { default as UsuarioInput } from './usuario.input';
export { default as ChatInput } from './chat.input';
export { default as ChatMensagemInput } from './chatmensagem.input';
