export { default as Tarefa } from './tarefa';
export { default as Cliente } from './cliente';
export { default as Setor } from './setor';
export { default as Classificacao } from './classificacao';
export { default as HomePage } from './home';
export { default as Login } from './login';
export { default as PagePerfil } from './perfil'
export { default as PageCadUsr } from './cadastros/usuario/usuario';
export { default as Sucesso } from './cadastros/usuario/sucesso';